services:
  - type: web
    name: tax-dashboard-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
    rootDir: backend

  - type: web
    name: tax-dashboard-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: frontend
